//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the visao_obr package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __visao_obr__CALIBRACAODATACONFIG_H__
#define __visao_obr__CALIBRACAODATACONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace visao_obr
{
  class CalibracaoDataConfigStatics;

  class CalibracaoDataConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(CalibracaoDataConfig &config, const CalibracaoDataConfig &max, const CalibracaoDataConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const CalibracaoDataConfig &config1, const CalibracaoDataConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, CalibracaoDataConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const CalibracaoDataConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CalibracaoDataConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const CalibracaoDataConfig &config) const = 0;
      virtual void getValue(const CalibracaoDataConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T CalibracaoDataConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (CalibracaoDataConfig::* field);

      virtual void clamp(CalibracaoDataConfig &config, const CalibracaoDataConfig &max, const CalibracaoDataConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const CalibracaoDataConfig &config1, const CalibracaoDataConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, CalibracaoDataConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const CalibracaoDataConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CalibracaoDataConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const CalibracaoDataConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const CalibracaoDataConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, CalibracaoDataConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, CalibracaoDataConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<CalibracaoDataConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(CalibracaoDataConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("cali_rect"==(*_i)->name){cali_rect = boost::any_cast<int>(val);}
        if("cali_circ_canny"==(*_i)->name){cali_circ_canny = boost::any_cast<int>(val);}
        if("cali_circ_hough"==(*_i)->name){cali_circ_hough = boost::any_cast<int>(val);}
        if("bool_param"==(*_i)->name){bool_param = boost::any_cast<bool>(val);}
        if("size"==(*_i)->name){size = boost::any_cast<int>(val);}
      }
    }

    int cali_rect;
int cali_circ_canny;
int cali_circ_hough;
bool bool_param;
int size;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int cali_rect;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int cali_circ_canny;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int cali_circ_hough;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool bool_param;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int size;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("CalibracaoDataConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const CalibracaoDataConfig &__max__ = __getMax__();
      const CalibracaoDataConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const CalibracaoDataConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const CalibracaoDataConfig &__getDefault__();
    static const CalibracaoDataConfig &__getMax__();
    static const CalibracaoDataConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const CalibracaoDataConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void CalibracaoDataConfig::ParamDescription<std::string>::clamp(CalibracaoDataConfig &config, const CalibracaoDataConfig &max, const CalibracaoDataConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class CalibracaoDataConfigStatics
  {
    friend class CalibracaoDataConfig;

    CalibracaoDataConfigStatics()
    {
CalibracaoDataConfig::GroupDescription<CalibracaoDataConfig::DEFAULT, CalibracaoDataConfig> Default("Default", "", 0, 0, true, &CalibracaoDataConfig::groups);
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cali_rect = 0;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cali_rect = 255;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cali_rect = 50;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CalibracaoDataConfig::AbstractParamDescriptionConstPtr(new CalibracaoDataConfig::ParamDescription<int>("cali_rect", "int", 0, "Calibracao do Rectangulo", "", &CalibracaoDataConfig::cali_rect)));
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CalibracaoDataConfig::AbstractParamDescriptionConstPtr(new CalibracaoDataConfig::ParamDescription<int>("cali_rect", "int", 0, "Calibracao do Rectangulo", "", &CalibracaoDataConfig::cali_rect)));
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cali_circ_canny = 0;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cali_circ_canny = 255;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cali_circ_canny = 50;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CalibracaoDataConfig::AbstractParamDescriptionConstPtr(new CalibracaoDataConfig::ParamDescription<int>("cali_circ_canny", "int", 0, "Calibracao do circulo canny", "", &CalibracaoDataConfig::cali_circ_canny)));
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CalibracaoDataConfig::AbstractParamDescriptionConstPtr(new CalibracaoDataConfig::ParamDescription<int>("cali_circ_canny", "int", 0, "Calibracao do circulo canny", "", &CalibracaoDataConfig::cali_circ_canny)));
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cali_circ_hough = 0;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cali_circ_hough = 255;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cali_circ_hough = 50;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CalibracaoDataConfig::AbstractParamDescriptionConstPtr(new CalibracaoDataConfig::ParamDescription<int>("cali_circ_hough", "int", 0, "Calibracao do circulo hough", "", &CalibracaoDataConfig::cali_circ_hough)));
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CalibracaoDataConfig::AbstractParamDescriptionConstPtr(new CalibracaoDataConfig::ParamDescription<int>("cali_circ_hough", "int", 0, "Calibracao do circulo hough", "", &CalibracaoDataConfig::cali_circ_hough)));
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.bool_param = 0;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.bool_param = 1;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.bool_param = 1;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CalibracaoDataConfig::AbstractParamDescriptionConstPtr(new CalibracaoDataConfig::ParamDescription<bool>("bool_param", "bool", 0, "A Boolean parameter", "", &CalibracaoDataConfig::bool_param)));
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CalibracaoDataConfig::AbstractParamDescriptionConstPtr(new CalibracaoDataConfig::ParamDescription<bool>("bool_param", "bool", 0, "A Boolean parameter", "", &CalibracaoDataConfig::bool_param)));
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.size = 0;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.size = 3;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.size = 1;
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CalibracaoDataConfig::AbstractParamDescriptionConstPtr(new CalibracaoDataConfig::ParamDescription<int>("size", "int", 0, "A size parameter which is edited via an enum", "{'enum_description': 'An enum to set size', 'enum': [{'srcline': 13, 'description': 'A small constant', 'srcfile': '/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Small'}, {'srcline': 14, 'description': 'A medium constant', 'srcfile': '/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Medium'}, {'srcline': 15, 'description': 'A large constant', 'srcfile': '/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Large'}, {'srcline': 16, 'description': 'An extra large constant', 'srcfile': '/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'ExtraLarge'}]}", &CalibracaoDataConfig::size)));
//#line 292 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CalibracaoDataConfig::AbstractParamDescriptionConstPtr(new CalibracaoDataConfig::ParamDescription<int>("size", "int", 0, "A size parameter which is edited via an enum", "{'enum_description': 'An enum to set size', 'enum': [{'srcline': 13, 'description': 'A small constant', 'srcfile': '/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Small'}, {'srcline': 14, 'description': 'A medium constant', 'srcfile': '/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Medium'}, {'srcline': 15, 'description': 'A large constant', 'srcfile': '/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Large'}, {'srcline': 16, 'description': 'An extra large constant', 'srcfile': '/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'ExtraLarge'}]}", &CalibracaoDataConfig::size)));
//#line 245 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/lunar/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(CalibracaoDataConfig::AbstractGroupDescriptionConstPtr(new CalibracaoDataConfig::GroupDescription<CalibracaoDataConfig::DEFAULT, CalibracaoDataConfig>(Default)));
//#line 356 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<CalibracaoDataConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<CalibracaoDataConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<CalibracaoDataConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    CalibracaoDataConfig __max__;
    CalibracaoDataConfig __min__;
    CalibracaoDataConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const CalibracaoDataConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static CalibracaoDataConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &CalibracaoDataConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const CalibracaoDataConfig &CalibracaoDataConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const CalibracaoDataConfig &CalibracaoDataConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const CalibracaoDataConfig &CalibracaoDataConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<CalibracaoDataConfig::AbstractParamDescriptionConstPtr> &CalibracaoDataConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<CalibracaoDataConfig::AbstractGroupDescriptionConstPtr> &CalibracaoDataConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const CalibracaoDataConfigStatics *CalibracaoDataConfig::__get_statics__()
  {
    const static CalibracaoDataConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = CalibracaoDataConfigStatics::get_instance();

    return statics;
  }

//#line 13 "/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg"
      const int CalibracaoData_Small = 0;
//#line 14 "/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg"
      const int CalibracaoData_Medium = 1;
//#line 15 "/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg"
      const int CalibracaoData_Large = 2;
//#line 16 "/home/lennedy/software/catkin_ws/src/visao_obr/cfg/CalibracaoData.cfg"
      const int CalibracaoData_ExtraLarge = 3;
}

#endif // __CALIBRACAODATARECONFIGURATOR_H__
