// Generated by gencpp from file visao_obr/CaliRect.msg
// DO NOT EDIT!


#ifndef VISAO_OBR_MESSAGE_CALIRECT_H
#define VISAO_OBR_MESSAGE_CALIRECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace visao_obr
{
template <class ContainerAllocator>
struct CaliRect_
{
  typedef CaliRect_<ContainerAllocator> Type;

  CaliRect_()
    : limiarDefinicao(0)  {
    }
  CaliRect_(const ContainerAllocator& _alloc)
    : limiarDefinicao(0)  {
  (void)_alloc;
    }



   typedef int32_t _limiarDefinicao_type;
  _limiarDefinicao_type limiarDefinicao;





  typedef boost::shared_ptr< ::visao_obr::CaliRect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visao_obr::CaliRect_<ContainerAllocator> const> ConstPtr;

}; // struct CaliRect_

typedef ::visao_obr::CaliRect_<std::allocator<void> > CaliRect;

typedef boost::shared_ptr< ::visao_obr::CaliRect > CaliRectPtr;
typedef boost::shared_ptr< ::visao_obr::CaliRect const> CaliRectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visao_obr::CaliRect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visao_obr::CaliRect_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace visao_obr

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'visao_obr': ['/home/lennedy/software/catkin_ws/src/visao_obr/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::visao_obr::CaliRect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visao_obr::CaliRect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visao_obr::CaliRect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visao_obr::CaliRect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visao_obr::CaliRect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visao_obr::CaliRect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visao_obr::CaliRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cd68788db00242817bb0bbdaf3abffe";
  }

  static const char* value(const ::visao_obr::CaliRect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cd68788db002428ULL;
  static const uint64_t static_value2 = 0x17bb0bbdaf3abffeULL;
};

template<class ContainerAllocator>
struct DataType< ::visao_obr::CaliRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visao_obr/CaliRect";
  }

  static const char* value(const ::visao_obr::CaliRect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visao_obr::CaliRect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Limiar de definição entre branco e preto utilizado pela função treshould do openCV\n\
int32 limiarDefinicao\n\
\n\
";
  }

  static const char* value(const ::visao_obr::CaliRect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visao_obr::CaliRect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.limiarDefinicao);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CaliRect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visao_obr::CaliRect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visao_obr::CaliRect_<ContainerAllocator>& v)
  {
    s << indent << "limiarDefinicao: ";
    Printer<int32_t>::stream(s, indent + "  ", v.limiarDefinicao);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISAO_OBR_MESSAGE_CALIRECT_H
