// Generated by gencpp from file visao_obr/CaliCirc.msg
// DO NOT EDIT!


#ifndef VISAO_OBR_MESSAGE_CALICIRC_H
#define VISAO_OBR_MESSAGE_CALICIRC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace visao_obr
{
template <class ContainerAllocator>
struct CaliCirc_
{
  typedef CaliCirc_<ContainerAllocator> Type;

  CaliCirc_()
    : limiarCanny(0)
    , limiarHough(0)  {
    }
  CaliCirc_(const ContainerAllocator& _alloc)
    : limiarCanny(0)
    , limiarHough(0)  {
  (void)_alloc;
    }



   typedef int32_t _limiarCanny_type;
  _limiarCanny_type limiarCanny;

   typedef int32_t _limiarHough_type;
  _limiarHough_type limiarHough;





  typedef boost::shared_ptr< ::visao_obr::CaliCirc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visao_obr::CaliCirc_<ContainerAllocator> const> ConstPtr;

}; // struct CaliCirc_

typedef ::visao_obr::CaliCirc_<std::allocator<void> > CaliCirc;

typedef boost::shared_ptr< ::visao_obr::CaliCirc > CaliCircPtr;
typedef boost::shared_ptr< ::visao_obr::CaliCirc const> CaliCircConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visao_obr::CaliCirc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visao_obr::CaliCirc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace visao_obr

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'visao_obr': ['/home/lennedy/software/catkin_ws/src/visao_obr/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::visao_obr::CaliCirc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visao_obr::CaliCirc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visao_obr::CaliCirc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visao_obr::CaliCirc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visao_obr::CaliCirc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visao_obr::CaliCirc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visao_obr::CaliCirc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d26cd7f2239cf78c7fd3bf7c292f589";
  }

  static const char* value(const ::visao_obr::CaliCirc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d26cd7f2239cf78ULL;
  static const uint64_t static_value2 = 0xc7fd3bf7c292f589ULL;
};

template<class ContainerAllocator>
struct DataType< ::visao_obr::CaliCirc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visao_obr/CaliCirc";
  }

  static const char* value(const ::visao_obr::CaliCirc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visao_obr::CaliCirc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Limiar de definição entre branco e preto utilizado pela função treshould do openCV\n\
int32 limiarCanny\n\
int32 limiarHough\n\
";
  }

  static const char* value(const ::visao_obr::CaliCirc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visao_obr::CaliCirc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.limiarCanny);
      stream.next(m.limiarHough);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CaliCirc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visao_obr::CaliCirc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visao_obr::CaliCirc_<ContainerAllocator>& v)
  {
    s << indent << "limiarCanny: ";
    Printer<int32_t>::stream(s, indent + "  ", v.limiarCanny);
    s << indent << "limiarHough: ";
    Printer<int32_t>::stream(s, indent + "  ", v.limiarHough);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISAO_OBR_MESSAGE_CALICIRC_H
